import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Image from "next/image";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Felix ITS - Frontend template</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <Link
          href={"https://github.com/usmonovdev/felix-nextjs-template"}
          className={`${styles.github}`}
        >
          <Image
            src={"/images/github-mark.png"}
            width={32}
            height={32}
            alt="Github"
          />
          <p>GitHub</p>
        </Link>
        <code>
          npx degit usmonovdev/felix-nextjs-template {"<LOYIHA NOMI>"}
        </code>
        <p>{`"Felix ITS"`} - Frontend template</p>
      </main>
    </>
  );
}
